routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Route::get('email', function() {
//    return new \App\Mail\LoginCredentials(\App\User::first(), '123456');
//});

//Route::get('about', 'PagesController@about')->name('pages.about');
//Route::get('archive', 'PagesController@archive')->name('pages.archive');
//Route::get('contact', 'PagesController@contact')->name('pages.contact');
//
//
//Route::get('blog/{post}', 'PostsController@show')->name('posts.show');
//Route::get('categorias/{category}', 'CategoriesController@show')->name('categories.show');
//Route::get('tags/{tag}', 'TagsController@show')->name('tags.show');

Route::auth([
    'register' => false,
    'reset' => false
]);

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => 'auth'], function() {

    Route::get('/', 'AdminController@index')->name('admin');

    Route::resource('posts', 'PostsController', [ "except" => "show", "as" => "admin" ]);
    Route::resource('users', 'UsersController', ['as' => 'admin']);
    Route::resource('roles', 'RolesController', ['as' => 'admin', "except" => "show"]);
    Route::resource('permissions', 'PermissionsController', ['as' => 'admin', "only" => ['index', 'edit', 'update']]);

    Route::middleware('role_or_permission:Admin|Update roles')
        ->put('users/{user}/roles', 'UsersRolesController@update')
        ->name('admin.users.roles.update');

    Route::middleware('role_or_permission:Admin|Update permissions')
        ->put('users/{user}/permissions', 'UsersPermissionsController@update')
        ->name('admin.users.permissions.update');

    Route::post('posts/{post}/photos', 'PhotosController@store')->name('admin.posts.photos.update');
    Route::delete('photos/{photo}', 'PhotosController@destroy')->name('admin.posts.photos.destroy');
});

Route::get('/{any?}', 'PagesController@spa')->name('pages.home')->where('any', '.*');

app/Http/Controllers/Admin/RolesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\SaveRolesRequest;
use App\User;
use Illuminate\Auth\Access\AuthorizationException;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RolesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('view', new Role);

        return view('admin.roles.index', [
            'roles' => Role::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', $role = new Role);

        return view('admin.roles.create', [
            'permissions' => Permission::pluck('name', 'id'),
            'role' => $role
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SaveRolesRequest $request)
    {
        $this->authorize('create', new Role);

        $role = Role::create($request->validated());

        $role->givePermissionTo($request->permissions);

        return redirect()->route('admin.roles.index')->withFlash('Role creado exitosamente.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        $this->authorize('update', $role);

        return view('admin.roles.edit', [
            'role' => $role,
            'permissions' => Permission::pluck('name', 'id')
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SaveRolesRequest $request, Role $role)
    {
        $this->authorize('update', $role);

        $role->update($request->validated());

        $role->permissions()->detach();

        $role->givePermissionTo($request->permissions);

        return redirect()->route('admin.roles.edit', $role)->withFlash('El role fue actualizado correctamente.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $this->authorize('delete', $role);

        $role->delete();

        return redirect()
            ->route('admin.roles.index')
            ->withFlash('El role fue eliminado exitosamente.');
    }
}

resources/views/admin/roles/checkboxes.blade.php
<div class="checkbox">
    @foreach($roles as $role)

        <label>
            <input type="checkbox"
                   value="{{ $role->name }}"
                   name="roles[]"
                {{ $user->roles->contains($role->id) ? 'checked' : '' }}>
            {{ $role->name }} <br>
            <small class="text-muted">{{ $role->permissions->pluck('name')->implode(', ') }}</small>
        </label>
        <br>

    @endforeach
</div>

resources/views/admin/roles/create.blade.php
@extends('admin.layout')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">
                        Crear Role
                    </h3>
                </div>
                <div class="box-body">
                    @include('partials.error-messages')
                    <form action="{{ route('admin.roles.store') }}" method="POST">

                        @include('admin.roles.form')

                        <button class="btn btn-primary btn-block">Crear role</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/roles/edit.blade.php
@extends('admin.layout')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">
                        Actualizar Role
                    </h3>
                </div>
                <div class="box-body">
                    @include('partials.error-messages')
                    <form action="{{ route('admin.roles.update', $role) }}" method="POST">
                        @method('PUT')

                        @include('admin.roles.form')

                        <button class="btn btn-primary btn-block">Actualizar role</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/roles/form.blade.php
@csrf
<div class="form-group">
    <label for="identificador">Identificador:</label>

    @if($role->exists)
        <input type="text"
               id="identificador"
               value="{{ $role->name }}"
               class="form-control" disabled>
    @else
        <input type="text"
               id="identificador"
               name="name"
               value="{{ old('name', $role->name) }}"
               class="form-control">
    @endif

</div>

<div class="form-group">
    <label for="display_name">Nombre:</label>
    <input type="text"
           name="display_name"
           class="form-control"
           value="{{ old('display_name', $role->display_name) }}">
</div>

<div class="form-group">
    <label for="permissions">Permisos:</label>
    @include('admin.permissions.checkboxes', ['model' => $role])
</div>

resources/views/admin/roles/index.blade.php
@extends('admin.layout')

@section('header')
    <h1>
        ROLES
        <small>Listado</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('admin') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
        <li class="active">Roles</li>
    </ol>
@stop

@section('content')
    <h1>Dashboard</h1>

    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Listado de roles</h3>

            @can('create', $roles->first())
                <a href="{{ route('admin.roles.create') }}" class="btn btn-primary pull-right">
                    <i class="fa fa-plus"></i> Crear role
                </a>
            @endcan

        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="roles-table" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Identificador</th>
                    <th>Nombre</th>
                    <th>Permisos</th>
                    <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                @foreach($roles as $role)
                    <tr>
                        <td>{{ $role->id }}</td>
                        <td>{{ $role->name }}</td>
                        <td>{{ $role->display_name }}</td>
                        <td>{{ $role->permissions->pluck('display_name')->implode(', ') }}</td>
                        <td>

                            @can('update', $role)
                                <a href="{{ route('admin.roles.edit', $role) }}" class="btn btn-xs btn-info"><i class="fa fa-pencil"></i></a>
                            @endcan

                            @can('delete', $role)
                                @if ($role->id != 1)
                                    <form method="POST"
                                          action="{{ route('admin.roles.destroy', $role) }}"
                                          style="display: inline;">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-xs btn-danger"
                                                onclick="return confirm('Estás seguro de querer eliminar este role?')">
                                            <i class="fa fa-times"></i>
                                        </button>
                                    </form>
                                @endif
                            @endcan
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
@stop

@push('styles')
    <!-- DataTables -->
    <link rel="stylesheet" href="/adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@endpush

@push('scripts')
    <!-- DataTables -->
    <script src="/adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

    <script>
        $(function () {
            $('#roles-table').DataTable();
        })
    </script>
@endpush