routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Route::get('email', function() {
//    return new \App\Mail\LoginCredentials(\App\User::first(), '123456');
//});

//Route::get('about', 'PagesController@about')->name('pages.about');
//Route::get('archive', 'PagesController@archive')->name('pages.archive');
//Route::get('contact', 'PagesController@contact')->name('pages.contact');
//
//
//Route::get('blog/{post}', 'PostsController@show')->name('posts.show');
//Route::get('categorias/{category}', 'CategoriesController@show')->name('categories.show');
//Route::get('tags/{tag}', 'TagsController@show')->name('tags.show');

Route::auth([
    'register' => false,
    'reset' => false
]);

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => 'auth'], function() {

    Route::get('/', 'AdminController@index')->name('admin');

    Route::resource('posts', 'PostsController', [ "except" => "show", "as" => "admin" ]);
    Route::resource('users', 'UsersController', ['as' => 'admin']);
    Route::resource('roles', 'RolesController', ['as' => 'admin', "except" => "show"]);
    Route::resource('permissions', 'PermissionsController', ['as' => 'admin', "only" => ['index', 'edit', 'update']]);

    Route::middleware('role_or_permission:Admin|Update roles')
        ->put('users/{user}/roles', 'UsersRolesController@update')
        ->name('admin.users.roles.update');

    Route::middleware('role_or_permission:Admin|Update permissions')
        ->put('users/{user}/permissions', 'UsersPermissionsController@update')
        ->name('admin.users.permissions.update');

    Route::post('posts/{post}/photos', 'PhotosController@store')->name('admin.posts.photos.update');
    Route::delete('photos/{photo}', 'PhotosController@destroy')->name('admin.posts.photos.destroy');
});

Route::get('/{any?}', 'PagesController@spa')->name('pages.home')->where('any', '.*');

app/User.php
<?php

namespace App;

use Spatie\Permission\Traits\HasRoles;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = bcrypt($password);
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function scopeAllowed($query)
    {
        if( auth()->user()->can('view', $this))
            return $query;

        return $query->where('id', auth()->id());
    }

    public function getRoleDisplayNames()
    {
        return $this->roles->pluck('display_name')->implode(', ');
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Events\UserWasCreated;
use App\Http\Requests\UpdateUserRequest;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::allowed()->get();

        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = new User();

        $this->authorize('create', $user);

        $roles = Role::with('permissions')->get();
        $permissions = Permission::pluck('name', 'id');

        return view('admin.users.create', compact('user', 'roles', 'permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', new User);

        $data = $request->validate([
            'name' => 'required|max:255',
            'email' => 'required|email|max:255|unique:users'
        ]);

        $data['password'] = str_random(8);

        $user = User::create($data);

        $user->assignRole($request->roles);

        $user->givePermissionTo($request->permissions);

        UserWasCreated::dispatch($user, $data['password']);

        return redirect()->route('admin.users.index')->withFlash('El usaurio ha sido creado.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $this->authorize('view', $user);

        return view('admin.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $this->authorize('update', $user);

        $roles = Role::with('permissions')->get();
        $permissions = Permission::pluck('name', 'id');

        return view('admin.users.edit', compact('user', 'roles', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, User $user)
    {
        $this->authorize('update', $user);

        $user->update( $request->validated() );

        return back()->withFlash('Usuario Actualizado.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $this->authorize('delete', $user);

        $user->delete();

        return redirect()->route('admin.users.index')->withFlash('Usuario eliminado.');
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layout')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">
                        Datos personales
                    </h3>
                </div>
                <div class="box-body">
                    @include('partials.error-messages')
                    <form action="{{ route('admin.users.store', $user) }}" method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="name">Nombre:</label>
                            <input type="text"
                                   name="name"
                                   value="{{ old('name') }}"
                                   class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="email">Email:</label>
                            <input type="text"
                                   name="email"
                                   value="{{ old('email') }}"
                                   class="form-control">
                        </div>

                        <div class="form-group col-md-6">
                            <label for="roles">Roles:</label>
                            @include('admin.roles.checkboxes')
                        </div>

                        <div class="form-group col-md-6">
                            <label for="permissions">Permisos:</label>
                            @include('admin.permissions.checkboxes', ['model' => $user])
                        </div>

                        <span class="help-block">La contraseña será generada y enviada al nuevo usuario vía email</span>
                        <button class="btn btn-primary btn-block">Crear Usuario</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/users/edit.blade.php
@extends('admin.layout')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">
                        Datos personales
                    </h3>
                </div>
                <div class="box-body">
                    @include('partials.error-messages')
                    <form action="{{ route('admin.users.update', $user) }}" method="POST">
                        @method('PUT')
                        @csrf
                        <div class="form-group">
                            <label for="name">Nombre:</label>
                            <input type="text"
                                   name="name"
                                   value="{{ old('name', $user->name) }}"
                                   class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="email">Email:</label>
                            <input type="text"
                                   name="email"
                                   value="{{ old('email', $user->email) }}"
                                   class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="password">Contraseña:</label>
                            <input type="password"
                                   name="password"
                                   class="form-control"
                                   placeholder="Contraseña">
                            <span class="help-block">
                                Dejar en blanco si noquiered cambiar la contraseña.
                            </span>
                        </div>
                        <div class="form-group">
                            <label for="password_confirmation">Repite la contraseña</label>
                            <input type="password"
                                   name="password_confirmation"
                                   class="form-control"
                                   placeholder="Repite la Contraseña">
                        </div>
                        <button class="btn btn-primary btn-block">Actualizar Usuario</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <div class="box-title">Roles</div>
                </div>
                <div class="box-body">
                    @if(auth()->user()->can('Update roles') || auth()->user()->hasRole('Admin'))
                        <form action="{{ route('admin.users.roles.update', $user) }}" method="POST">
                            @method('PUT')
                            @csrf

                            @include('admin.roles.checkboxes')

                            <button class="btn btn-primary btn-block">Actualizar Roles</button>
                        </form>
                    @else
                        <ul class="list-group">
                            @forelse ($user->roles as $role)
                                <li class="list-group-item">{{ $role->name }}</li>
                            @empty
                                <li class="list-group-item">No tiene roles</li>
                            @endforelse
                        </ul>
                    @endif
                </div>
            </div>
            <div class="box box-primary">
                <div class="box-header with-border">
                    <div class="box-title">Permisos</div>
                </div>
                <div class="box-body">
                    @if(auth()->user()->can('Update roles') || auth()->user()->hasRole('Admin'))
                        <form action="{{ route('admin.users.permissions.update', $user) }}" method="POST">
                            @method('PUT')
                            @csrf

                            @include('admin.permissions.checkboxes', ['model' => $user])

                            <button class="btn btn-primary btn-block">Actualizar Permisos</button>
                        </form>
                    @else
                        <ul class="list-group">
                            @forelse($user->permissions as $permission)
                                <li class="list-group-item">{{ $permission->name }}</li>
                            @empty
                                <li class="list-group-item">No tiene permisos</li>
                            @endforelse
                        </ul>
                    @endif
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/users/index.blade.php
@extends('admin.layout')

@section('header')
    <h1>
        USUARIOS
        <small>Listado</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('admin') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
        <li class="active">Usuarios</li>
    </ol>
@stop

@section('content')
    <h1>Dashboard</h1>

    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Listado de usuarios</h3>
            @can('create', $users->first())
                <a href="{{ route('admin.users.create') }}" class="btn btn-primary pull-right">
                    <i class="fa fa-plus"></i> Crear usuario
                </a>
            @endcan
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="users-table" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Email</th>
                    <th>Roles</th>
                    <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->getRoleNames()->implode(', ') }}</td>
                        <td>

                            @can('view', $user)
                                <a href="{{ route('admin.users.show', $user) }}"
                                   class="btn btn-xs btn-default">
                                    <i class="fa fa-eye"></i>
                                </a>
                            @endcan

                            @can('update', $user)
                                <a href="{{ route('admin.users.edit', $user) }}" class="btn btn-xs btn-info"><i class="fa fa-pencil"></i></a>
                            @endcan

                            @can('delete', $user)
                                <form method="POST"
                                      action="{{ route('admin.users.destroy', $user) }}"
                                      style="display: inline;">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-xs btn-danger"
                                            onclick="return confirm('Estás seguro de querer eliminar este usuario?')">
                                        <i class="fa fa-times"></i>
                                    </button>
                                </form>
                            @endcan
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
@stop

@push('styles')
    <!-- DataTables -->
    <link rel="stylesheet" href="/adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@endpush

@push('scripts')
    <!-- DataTables -->
    <script src="/adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

    <script>
        $(function () {
            $('#users-table').DataTable();
        })
    </script>
@endpush

resources/views/admin/users/show.blade.php
@extends('admin.layout')

@section('content')
    <div class="row">
        <div class="col-md-3">
            <div class="box box-primary">
                <div class="box-body box-profile">
                    <img class="profile-user-img img-responsive img-circle"
                         src="/adminlte/img/user4-128x128.png"
                         alt="{{ $user->name }}">

                    <h3 class="profile-username text-center">{{ $user->name }}</h3>

                    @if($user->roles->count())
                        <p class="text-muted text-center">
                            {{ $user->getRoleNames()->implode(', ') }}
                        </p>
                    @endif

                    <ul class="list-group list-group-unbordered">
                        <li class="list-group-item">
                            <b>Email</b> <a class="pull-right">{{ $user->email }}</a>
                        </li>
                        <li class="list-group-item">
                            <b>Publicaciones</b> <a class="pull-right">{{ $user->posts->count() }}</a>
                        </li>

                        @if($user->roles->count())
                            <li class="list-group-item">
                                <b>Roles</b> <a class="pull-right">{{ $user->getRoleNames()->implode(', ') }}</a>
                            </li>
                        @endif
                    </ul>

                    <a href="{{ route('admin.users.edit', $user) }}" class="btn btn-primary btn-block"><b>Editar</b></a>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
        <div class="col-md-3">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Publicaciones</h3>
                </div>
                <div class="box-body">
                    @forelse( $user->posts as $post)
                        <a href="{{ config('app.APP_URL') }}/blog/{{$post->url}}"
                            target="_blank">
                            <strong>{{ $post->title }}</strong>
                        </a><br>
                        <small class="text-muted">
                            Publicado el {{ $post->published_at->format('d/m/Y') }}
                        </small>
                        <p class="text-muted">
                            {{$post->excerpt}}
                        </p>
                        @unless($loop->last)
                            <hr>
                        @endunless
                    @empty
                        <small class="text-muted">
                            No tiene publicaciones
                        </small>
                    @endforelse
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Roles</h3>
                </div>
                <div class="box-body">
                    @forelse($user->roles as $role)
                        <strong>{{ $role->name }}</strong>
                        @if( $role->permissions->count() )
                            <br>
                            <small class="text-muted">
                                Permisos: {{ $role->permissions->pluck('name')->implode(', ') }}
                            </small>
                        @endif
                        @unless($loop->last)
                            <hr>
                        @endunless
                    @empty
                        <small class="text-muted">
                            No tiene ningun rol asignado
                        </small>
                    @endforelse
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Permisos Adicionales</h3>
                </div>
                <div class="box-body">
                    @forelse($user->permissions as $permission)
                        <strong>{{ $permission->name }}</strong>
                        @unless($loop->last)
                            <hr>
                        @endunless
                    @empty
                        <small class="text-muted">
                            No tiene permisos adicionales
                        </small>
                    @endforelse
                </div>
            </div>
        </div>
    </div>
@stop