routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Route::get('email', function() {
//    return new \App\Mail\LoginCredentials(\App\User::first(), '123456');
//});

//Route::get('about', 'PagesController@about')->name('pages.about');
//Route::get('archive', 'PagesController@archive')->name('pages.archive');
//Route::get('contact', 'PagesController@contact')->name('pages.contact');
//
//
//Route::get('blog/{post}', 'PostsController@show')->name('posts.show');
//Route::get('categorias/{category}', 'CategoriesController@show')->name('categories.show');
//Route::get('tags/{tag}', 'TagsController@show')->name('tags.show');

Route::auth([
    'register' => false,
    'reset' => false
]);

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => 'auth'], function() {

    Route::get('/', 'AdminController@index')->name('admin');

    Route::resource('posts', 'PostsController', [ "except" => "show", "as" => "admin" ]);
    Route::resource('users', 'UsersController', ['as' => 'admin']);
    Route::resource('roles', 'RolesController', ['as' => 'admin', "except" => "show"]);
    Route::resource('permissions', 'PermissionsController', ['as' => 'admin', "only" => ['index', 'edit', 'update']]);

    Route::middleware('role_or_permission:Admin|Update roles')
        ->put('users/{user}/roles', 'UsersRolesController@update')
        ->name('admin.users.roles.update');

    Route::middleware('role_or_permission:Admin|Update permissions')
        ->put('users/{user}/permissions', 'UsersPermissionsController@update')
        ->name('admin.users.permissions.update');

    Route::post('posts/{post}/photos', 'PhotosController@store')->name('admin.posts.photos.update');
    Route::delete('photos/{photo}', 'PhotosController@destroy')->name('admin.posts.photos.destroy');
});

Route::get('/{any?}', 'PagesController@spa')->name('pages.home')->where('any', '.*');

app/Post.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Post extends Model
{
    protected $fillable = ['title', 'body', 'iframe', 'excerpt', 'published_at', 'category_id', 'user_id'];

    protected $dates = ['published_at'];

    protected $appends = ['published_date'];

    protected static function boot()
    {
        parent::boot();

        static::deleting(function($post) {
            $post->tags()->detach();
            $post->photos->each->delete();
        });
    }

    public function getPublishedDateAttribute()
    {
        return optional($this->published_at)->format('M d');
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function scopePublished($query)
    {
        $query->with(['owner', 'category', 'tags', 'photos'])
            ->whereNotNull('published_at')
            ->where('published_at', '<=', Carbon::now())
            ->latest('published_at');
    }

    public function scopeAllowed($query)
    {
        if( auth()->user()->can('view', $this))
            return $query;

        return $query->where('user_id', auth()->id());
    }

    public function scopeByYearAndMonth($query)
    {
        return $query->selectRaw('year(published_at) as year')
            ->selectRaw('month(published_at) as month')
            ->selectRaw('monthName(published_at) as monthname')
            ->selectRaw('count(*) as posts')
            ->groupBy('year', 'month', 'monthname')
            ->orderBy('published_at');
    }


    public static function create(array $attributes = [])
    {
        $attributes['user_id'] = auth()->id();

        $post = static::query()->create($attributes);

        $post->generarUrl();

        return $post;
    }

    public function generarUrl()
    {
        $url = str_slug($this->title);

        if( $this::whereUrl($url)->exists())
        {
            $url = "{$url}-{$this->id}";
        }

        $this->url = $url;

        $this->save();
    }

    public function photos()
    {
        return $this->hasMany(Photo::class);
    }

    public function owner()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function isPublished()
    {
        return !is_null($this->published_at) && $this->published_at < today();
    }

    public function getRouteKeyName()
    {
        return 'url';
    }

    public function setPublishedAtAttribute($published_at)
    {
        $this->attributes['published_at'] = $published_at ? Carbon::parse($published_at) : null;
    }

    public function setCategoryIdAttribute($category)
    {
        $this->attributes['category_id'] = Category::find($category)
            ? $category
            : Category::create(["name" => $category])->id;
    }

    public function syncTags($tags)
    {
        $tagsIds = collect($tags)->map(function($tag) {
            return Tag::find($tag) ? $tag : Tag::create(["name" => $tag])->id;
        });

        return $this->tags()->sync($tagsIds);
    }

    public function viewType($home = '')
    {
        $view = null;

        if($this->photos->count() === 1):
            $view = 'posts.photo';
        elseif ($this->photos->count() > 1):
            $view = $home === 'home' ? 'posts.carousel-preview' : 'posts.carousel';
        elseif($this->iframe):
            $view =  'posts.iframe';
        endif;

        return $view;
    }

}

app/Http/Controllers/Admin/PostsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Requests\StorePostRequest;
use App\Post;
use App\Tag;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PostsController extends Controller
{
    public function index()
    {
        $posts = Post::allowed()->get();

        return view('admin.posts.index', compact('posts'));
    }

    public function store(Request $request)
    {
        $this->authorize('create', new Post);

        $this->validate($request, ['title' => 'required|min:3']);

        $post = Post::create($request->all());

        return redirect()->route('admin.posts.edit', $post);
    }

    public function edit(Post $post)

    {
        $this->authorize('update', $post);

        return view('admin.posts.edit', [
            'post' => $post,
            'tags' => Tag::all(),
            'categories' => Category::all()
        ]);
    }
    public function update(Post $post, StorePostRequest $request)
    {
        $this->authorize('update', $post);

        $post->update($request->all());

        $post->save();

        $post->syncTags($request->get('tags'));

        return redirect()
            ->route('admin.posts.edit', $post)
            ->with('flash', 'La publicación ha sido guardada');
    }

    public function destroy(Post $post)
    {
        $this->authorize('delete', $post);

        $post->delete();

        return redirect()
            ->route('admin.posts.index')
            ->with('flash', 'La publicación ha sido eliminada');
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Resources\PostResource;
use App\Post;
use Response;

class PostsController extends Controller
{
    public function show(Post $post)
    {
//        return new PostResource($post);

        if($post->isPublished() || auth()->check())
        {
            $post->load('owner', 'category', 'tags', 'photos');

            if(request()->wantsJson())
                return response::json([
                    'post' => $post
                ]);

            return view('posts.show', compact('post'));
        }


        abort(404);
    }
}

resources/views/admin/posts/create.blade.php
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <form action="{{ route('admin.posts.store', '#create') }}" method="POST">
        @csrf()
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">Agrega el título de tu nueva publicación</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                        {{--<label for="">Título de la publicación</label>--}}
                        <input type="text"
                               id="post-title"
                               name="title"
                               value="{{ old('title') }}"
                               class="form-control"
                               placeholder="Ingresa aquí el título de la publicación"
                                autofocus required>
                        {!! $errors->first('title', '<span class="help-block">:message</span>') !!}
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default" data-dismiss="modal">Close</button>
                    <button class="btn btn-primary">Crear Publicación</button>
                </div>
            </div>
        </div>
    </form>
</div>

@push('scripts')
    <script>
        if(window.location.hash === "#create")
        {
            $("#myModal").modal('show');
        }

        $("#myModal").on('hide.bs.modal', function() {
            window.location.hash = "#";
        });

        $("#myModal").on('shown.bs.modal', function() {
            $("#post-title").focus();
            window.location.hash = "#create";
        });
    </script>
@endpush

resources/views/admin/posts/edit.blade.php
@extends('admin.layout')

@section('header')
    <h1>
        Posts
        <small>Crear publicación</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('admin') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
        <li><a href="{{ route('admin.posts.index') }}"><i class="fa fa-list"></i> Posts</a></li>
        <li class="active">Crear</li>
    </ol>
@stop

@section('content')
    <div class="row">
        @if($post->photos->count())
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="row">
                            @foreach($post->photos as $photo)
                                <form method="POST" action="{{ route('admin.posts.photos.destroy', $photo) }}">
                                    @csrf
                                    @method('DELETE')
                                    <div class="col-md-2">
                                        <button class="btn btn-danger btn-xs" style="position: absolute;">
                                            <i class="fa fa-remove"></i>
                                        </button>
                                        <img src="{{ url($photo->path) }}" alt="" class="img-responsive">
                                    </div>
                                </form>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        @endif
        <form action="{{ route('admin.posts.update', $post) }}" method="POST">
            @csrf()
            @method('PUT')
            <div class="col-md-8">
                <div class="box box-primary">
                    <div class="box-body">

                        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                            <label for="">Título de la publicación</label>
                            <input type="text" name="title" value="{{ old('title', $post->title) }}" class="form-control" placeholder="Ingresa aquí el título de la publicación">
                            {!! $errors->first('title', '<span class="help-block">:message</span>') !!}
                        </div>
                        <div class="form-group"{{ $errors->has('body') ? ' has-error' : '' }}>
                            <label for="">Contenido de la publicación</label>
                            <textarea id="editor" name="body" rows="10" class="form-control" placeholder="Ingresa el contenido completo de la publicación">
                                {{ old('body', $post->body) }}
                            </textarea>
                            {!! $errors->first('body', '<span class="help-block">:message</span>') !!}
                        </div>
                        <div class="form-group"{{ $errors->has('iframe') ? ' has-error' : '' }}>
                            <label for="iframe">Contenido embebido (iframe)</label>
                            <textarea id="editor" name="iframe" rows="2" class="form-control" placeholder="Ingresa Contenido embebido (iframe) de audio o video">{{ old('iframe', $post->iframe) }}</textarea>
                            {!! $errors->first('iframe', '<span class="help-block">:message</span>') !!}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-body">
                        <!-- Date -->
                        <div class="form-group">
                            <label>Fecha de publicación:</label>

                            <div class="input-group date">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <input type="text" value="{{ old('published_at', $post->published_at ? $post->published_at->format('d/m/Y') : null) }}" name="published_at" class="form-control pull-right" id="datepicker">
                            </div>
                            <!-- /.input group -->
                        </div>
                        <!-- /.form group -->
                        <div class="form-group{{ $errors->has('category_id') ? ' has-error' : '' }}">
                            <label for="">Categorias</label>
                            <select name="category_id" class="form-control select2">
                                <option value="">Selecciona una categoría</option>
                                @foreach($categories as $category)
                                    <option value="{{ $category->id }}"
                                        {{ old('category_id', $post->category_id) == $category->id ? 'selected' : '' }}
                                    >{{ $category->name }}</option>
                                @endforeach
                            </select>
                            {!! $errors->first('category_id', '<span class="help-block">:message</span>') !!}
                        </div>
                        <div class="form-group{{ $errors->has('tags') ? ' has-error' : '' }}">
                            <label for="">Etiquetas</label>
                            <select name="tags[]" class="form-control select2"
                                    multiple="multiple"
                                    data-placeholder="Selecciona una o más etiquetas"
                                    style="width: 100%;">
                                @foreach($tags as $tag)
                                    <option
                                        {{ collect(old('tags', $post->tags->pluck('id')))->contains($tag->id) ? 'selected' : '' }}
                                        value="{{ $tag->id }}">{{ $tag->name }}</option>
                                @endforeach
                            </select>
                            {!! $errors->first('tags', '<span class="help-block">:message</span>') !!}
                        </div>
                        <div class="form-group{{ $errors->has('excerpt') ? ' has-error' : '' }}">
                            <label for="">Extracto de la publicación</label>
                            <textarea name="excerpt" class="form-control" placeholder="Ingresa un extracto de la publicación.">
                                {{ old('excerpt', $post->excerpt) }}
                            </textarea>
                            {!! $errors->first('excerpt', '<span class="help-block">:message</span>') !!}
                        </div>
                        <div class="form-group">
                            <div class="dropzone"></div>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary btn-block" type="submit">Guardar Publicación</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@stop

@push('styles')
    <!-- Dropzone -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.css">

    <!-- bootstrap datepicker -->
    <link rel="stylesheet" href="/adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">

    <!-- Select2 -->
    <link rel="stylesheet" href="/adminlte/bower_components/select2/dist/css/select2.min.css">
@endpush

@push('scripts')
    <!-- Dropzone -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.js"></script>

    <!-- bootstrap datepicker -->
    <script src="/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>

    <!-- CK Editor -->
    <script src="https://cdn.ckeditor.com/4.11.2/standard/ckeditor.js"></script>

    <!-- Select2 -->
    <script src="/adminlte/bower_components/select2/dist/js/select2.full.min.js"></script>

    <script>
        //Date picker
        $('#datepicker').datepicker({
            autoclose: true
        });
        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
        CKEDITOR.replace('editor');
        CKEDITOR.config.height = 315;

        //Initialize Select2 Elements
        $('.select2').select2({
            tags: true
        })

        var myDropzone = new Dropzone('.dropzone', {
            url: '/admin/posts/{{ $post->url }}/photos',
            headers: {
              'X-CSRF-TOKEN': '{{ csrf_token() }}'
            },
            acceptedFiles: 'image/*',
            maxFilesize: 2,
            paramName: 'photo',
            dictDefaultMessage: 'Arrastra las fotos aquí para subirlas'
        });

        myDropzone.on('error', function(file, res){
            var msg = res.errors.photo[0];
            $('.dz-error-message:last > span').text(msg);
        });

        Dropzone.autoDiscover = false;
    </script>
@endpush

resources/views/admin/posts/index.blade.php
@extends('admin.layout')

@section('header')
    <h1>
        Posts
        <small>Listado</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('admin') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
        <li class="active">Posts</li>
    </ol>
@stop

@section('content')
    <h1>Dashboard</h1>

    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Listado de publicaciones</h3>
            <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#myModal">
                <i class="fa fa-plus"></i> Crear publicación
            </button>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="posts-table" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Título</th>
                    <th>Extracto</th>
                    <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($posts as $post)
                        <tr>
                            <td>{{ $post->id }}</td>
                            <td>{{ $post->title }}</td>
                            <td>{{ $post->excerpt }}</td>
                            <td>
                                <a href="{{ config('app.APP_URL') }}/blog/{{$post->url}}"
                                   class="btn btn-xs btn-default"
                                   target="_blank"><i class="fa fa-eye"></i></a>
                                <a href="{{ route('admin.posts.edit', $post) }}" class="btn btn-xs btn-info"><i class="fa fa-pencil"></i></a>

                                <form method="POST"
                                    action="{{ route('admin.posts.destroy', $post) }}"
                                    style="display: inline;">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-xs btn-danger"
                                        onclick="return confirm('Estás seguro de querer eliminar esta publicación?')">
                                        <i class="fa fa-times"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
@stop

@push('styles')
    <!-- DataTables -->
    <link rel="stylesheet" href="/adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@endpush

@push('scripts')
    <!-- DataTables -->
    <script src="/adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

    <script>
        $(function () {
            $('#posts-table').DataTable();
        })
    </script>
@endpush