routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Route::get('email', function() {
//    return new \App\Mail\LoginCredentials(\App\User::first(), '123456');
//});

//Route::get('about', 'PagesController@about')->name('pages.about');
//Route::get('archive', 'PagesController@archive')->name('pages.archive');
//Route::get('contact', 'PagesController@contact')->name('pages.contact');
//
//
//Route::get('blog/{post}', 'PostsController@show')->name('posts.show');
//Route::get('categorias/{category}', 'CategoriesController@show')->name('categories.show');
//Route::get('tags/{tag}', 'TagsController@show')->name('tags.show');

Route::auth([
    'register' => false,
    'reset' => false
]);

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => 'auth'], function() {

    Route::get('/', 'AdminController@index')->name('admin');

    Route::resource('posts', 'PostsController', [ "except" => "show", "as" => "admin" ]);
    Route::resource('users', 'UsersController', ['as' => 'admin']);
    Route::resource('roles', 'RolesController', ['as' => 'admin', "except" => "show"]);
    Route::resource('permissions', 'PermissionsController', ['as' => 'admin', "only" => ['index', 'edit', 'update']]);

    Route::middleware('role_or_permission:Admin|Update roles')
        ->put('users/{user}/roles', 'UsersRolesController@update')
        ->name('admin.users.roles.update');

    Route::middleware('role_or_permission:Admin|Update permissions')
        ->put('users/{user}/permissions', 'UsersPermissionsController@update')
        ->name('admin.users.permissions.update');

    Route::post('posts/{post}/photos', 'PhotosController@store')->name('admin.posts.photos.update');
    Route::delete('photos/{photo}', 'PhotosController@destroy')->name('admin.posts.photos.destroy');
});

Route::get('/{any?}', 'PagesController@spa')->name('pages.home')->where('any', '.*');

app/Http/Controllers/Admin/PermissionsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Permission;

class PermissionsController extends Controller
{
    public function index()
    {
        $this->authorize('view', new Permission);

        return view('admin.permissions.index', [
            'permissions' => Permission::all()
        ]);
    }

    public function edit(Permission $permission)
    {
        $this->authorize('update', $permission);

        return view('admin.permissions.edit', [
            'permission' => $permission
        ]);
    }

    public function update(Request $request, Permission $permission)
    {
        $this->authorize('update', $permission);

        $data = $request->validate(['display_name' => 'required']);

        $permission->update($data);

        return redirect()
            ->route('admin.permissions.edit', $permission)
            ->withFlash('El permiso ha sido actualizado con éxito.');
    }

}

resources/views/admin/permissions/checkboxes.blade.php
<div class="checkbox">
    @foreach($permissions as $id => $name)

        <label>
            <input type="checkbox"
                   value="{{ $name }}"
                   name="permissions[]"
                {{ $model->permissions->contains($id) || collect(old('permissions'))->contains($name) ? 'checked' : '' }}>
            {{ $name }}
        </label>
        <br>

    @endforeach
</div>

resources/views/admin/permissions/edit.blade.php
@extends('admin.layout')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">
                        Actualizar Permiso
                    </h3>
                </div>
                <div class="box-body">
                    @include('partials.error-messages')
                    <form action="{{ route('admin.permissions.update', $permission) }}" method="POST">
                        @method('PUT')
                        @csrf

                        <div class="form-group">
                            <label for="name">Identificador:</label>
                            <input type="text"
                                   class="form-control"
                                   disabled
                                   value="{{ $permission->name }}">
                        </div>

                        <div class="form-group">
                            <label for="display_name">Nombre:</label>
                            <input type="text"
                                   name="display_name"
                                   class="form-control" value="{{ old('display_name', $permission->display_name) }}">
                        </div>

                        <button class="btn btn-primary btn-block">Actualizar permiso</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/permissions/index.blade.php
@extends('admin.layout')

@section('header')
    <h1>
        PERMISOS
        <small>Listado</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('admin') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
        <li class="active">Permisos</li>
    </ol>
@stop

@section('content')
    <h1>Dashboard</h1>

    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Listado de permisos</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="permisos-table" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Identificador</th>
                    <th>Nombre</th>
                    <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                @foreach($permissions as $permission)
                    <tr>
                        <td>{{ $permission->id }}</td>
                        <td>{{ $permission->name }}</td>
                        <td>{{ $permission->display_name }}</td>
                        <td>
                            @can('update', $permission)
                                <a href="{{ route('admin.permissions.edit', $permission) }}" class="btn btn-xs btn-info"><i class="fa fa-pencil"></i></a>
                            @endcan
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
@stop

@push('styles')
    <!-- DataTables -->
    <link rel="stylesheet" href="/adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@endpush

@push('scripts')
    <!-- DataTables -->
    <script src="/adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

    <script>
        $(function () {
            $('#permisos-table').DataTable();
        })
    </script>
@endpush